### PR TITLE
Travis Continuous Integration with Boa

### PR DESCRIPTION
**Pull request by ankuraga1508**

### CODE REVIEW

**Comment by psybers** [comment]
Why was the test 'test/codegen/allowed-stops.boa' changed?

**Comment by psybers** [comment]
Why was the test reDeclVar() disabled?  It is passing.  https://github.com/boalang/compiler/pull/51/files#diff-9573e03f3a1fc0860f571c956d04fa8cR54

**Comment by ankuraga1508** [comment]
Somehow this recently added file "test/codegen/allowed-stops.boa" was deleted by me while making the commit. So I added it back. There is no change done, some spacing might have altered though.

Yes Dr. Dyer I just checked  reDeclVar() test is passing. I partially remember seeing this test fail but that was a mistake. My apologies. I have added it in next commit. 

Thanks for the feedback.

**Comment by psybers** [comment]
Except if you look at the diff, there IS a change to the allowed-stops.boa file.  Not just whitespace - actual blocks of code are now missing.  Please revert that change.

**Comment by ankuraga1508** [comment]
I don't know why git is showing code is missing. I checked two files earlier one and this committed one but I don't see any block removed or code changed. I will revert this change.

**Comment by ankuraga1508** [comment]
I have made commit with proper spacing. Now git is not showing any diff.

**Comment by psybers** [comment]
Should the fail come after deleting the temporary file: https://github.com/boalang/compiler/pull/51/files#diff-2cccd7bf48b7a9cc113ff564acd802a8R179

In other words, lines 179/180 should be swapped?

**Comment by ankuraga1508** [comment]
Yeah that makes more sense. Will swap. Thanks.

**Comment by psybers** [comment]
I'm good with this now.  If one more person reviews it we can merge.

**Comment by psybers** [comment]
Actually one more comment regarding https://github.com/boalang/compiler/pull/51/files#diff-9573e03f3a1fc0860f571c956d04fa8cR59 - since you disabled the test by simply removing the ```@Test``` annotation, can you please *also* move the test case files into the failingtest directory?  Otherwise we may forget to ever re-enable these tests!

**Comment by ankuraga1508** [comment]
Dr. Dyer, I have moved those test files. Thanks.

**Comment by hridesh** [comment]
The branch now has a conflict. Could that be resolved please? Thanks.

**Comment by ankuraga1508** [comment]
Conflict is removed.

**Comment by hridesh** [comment]
This can now be merged.

**Pull request merged**
