### PR TITLE
boa tuple with shallow copy

### PR DESCRIPTION
**Pull request by hyjorc1**
Can we use the shallow copy for all members when we initialize a boa tuple? I need to add array as a member in boa tuple.

### CODE REVIEW

**Comment by psybers** [comment]
This PR related to #244

**Comment by psybers** [comment]
The semantics of Boa stipulates there are no references to data.  If I assign to a tuple, and then change the array I assigned to it, the tuple's array should not update. Thus we want a deep copy.  Ideally, we would use a 'copy on write' optimization to avoid actually copying unless it is needed.

**Comment by psybers** [comment]
I have considered doing away with raw arrays in the codegen and instead using `List` everywhere.  If that change happened, your problem would be solved?

**Comment by hyjorc1** [comment]
If we want to associate those protobuf types to more information or relations without any further updates, tuple with shallow copy could be a good choice. 

For example, if we want to build a method body tree shown as below, we could use a self-defined tuple as a linked list.
`type Node = {s: Statement, depth: int, loc: int, parent: Node};`

Screen Shot 2019-03-22 at 3 42 09 PM

**Comment by psybers** [comment]
We already have shallow copy for protobuf types.  That was added in PR #244

**Comment by hyjorc1** [comment]
Yep, but that's only for protobuf types not for self-defined types.

**Comment by psybers** [comment]
Well first, #101 means you cant even define your `Node` type as you did.  Second, even if that is fixed, there is no problem as the protobufs in the nested instances will also be shallow copied when the tuple gets deep copied.

**Comment by hridesh** [comment]
Should we consider performance (especially memory) implications of this choice?

On Mar 22, 2019, at 1:20 PM, Robert Dyer <notifications@github.com<mailto:notifications@github.com>> wrote:


I have considered doing away with raw arrays in the codegen and instead using List everywhere. If that change happened, your problem would be solved?

**Comment by psybers** [comment]
Performance issues are why I haven't implemented that change yet.

**Pull request closed without merging**
