### PR TITLE
Compiler hybrid traversal analysis

### PR DESCRIPTION
**Pull request by RamIowaStateUniversity**
Pull request - Added graph traversal and program analysis feature.

### CODE REVIEW

**Comment by hridesh** [comment]
Hi Ram,

Thanks for your work on this big feature. I have following comments on your merge request.
1. Please resolve merge conflicts. 
2. There are some unnecessary changes that can be reviewed and removed (e.g. in compile.sh)
3. This entire merge request might be easier to process if it is sent in a piecemeal manner.

We look forward to merging this feature with the Boa master branch.

**Comment by psybers** [comment]
I would like to see some good tests.  A bunch of 'known good' programs can definitely help test, but then when things break it becomes extremely hard to know *why* it broke.  Ideally there should be a test for each new feature.

**Comment by psybers** [comment]
src/antlr/BoaNoActions.g needs updated to reflect any changes in the grammar.  This is the file I typically look at first to understand how the grammar was changed.

Speaking of grammar changes, didn't we discuss making traversal/fixp just a normal function?  Why was there a need for new grammar constructs for traversal/fixp when it is obviously just a function?  Also the grammar itself needs carefully looked at.  You have copied/pasted from visitors and some of the error messages do not make sense in your new context.

**Comment by RamIowaStateUniversity** [comment]
Thanks for the comments. I will resolve these issues and notify in this
thread so that the boa group can start reviewing the code.

Thanks,
Ram
ᐧ

**Comment by psybers** [comment]
Unless I am mistaken, most or all of this PR is either already merged, or in the program-analysis branch.

**Pull request closed without merging**
