### PR TITLE
pull changes from master.

### PR DESCRIPTION
**Pull request by hridesh**

### CODE REVIEW

**Comment by hridesh** [comment]
It appears to be the case that the dev/datagen branch is using a newer Java version. Could we make the source code compatible with master branch?

**Comment by psybers** [comment]
That is correct. The master branch assumes Java 6, so newer Java 8 features should not be used at this time and hence these CI build failures.

To some degree this problem manifested because the old datagen repository did not have a Java 6 requirement.  Now that we merged them into a single repository we have to stick with Java 6 (for now) due to Hadoop reasons (it might be possible to move to Java 7, but it is untested).

**Comment by nmtiwari** [comment]
Dr. Dyer 
While developing the data generation code, I used diamond operator frequently. I believe others may also be using these features and we should make the current code compatible with Java 7. Could you please tell what parts are untested and how can we test them ? How much heavy will this work be ?

**Comment by hridesh** [comment]
Nitin, I agree. That is a good idea to move forward. Some of us under the leadership of Robert are investigating move to later version of Hadoop. Perhaps this change can happen at that time.

**Pull request merged**
