### PR TITLE
Update master from datagen2017 branch

### PR DESCRIPTION
**Pull request by nguyenhoan**

### CODE REVIEW

**Comment by nguyenhoan** [comment]
I think we auto-generated files for protobufs should not be versioned.

Why are there only 2 commits to be merged from datagen2017 to master?
It seems that the previous merge from master to datagen2017 also merged from datagen2017 to master.
What am I missing?

**Comment by psybers** [comment]
You merged datagen into master:

https://github.com/boalang/compiler/commit/3fab5c2df305a66a9773ed46b4c693e55fa10616

On Jun 25, 2017, at 1:41 PM, Hoan Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we auto-generated files for protobufs should not be versioned.

Why are there only 2 commits to be merged from datagen2017 to master?
It seems that the previous merge from master to datagen2017 also merged from datagen2017 to master.
What am I missing?

**Comment by psybers** [comment]
The reason we version the generated/compiled proto files is so that you are not required to have protobuf's compiler to build Boa's compiler.

**Comment by nguyenhoan** [comment]
I don't think I made that merge on purpose but by accident when merge the pull request from master to datagen.

Versioning the generated/compiled proto files caused unnecessary conflicts when modifying protobuf files.

**Pull request merged**
