### PR TITLE
fix issue #6 _v3

### PR DESCRIPTION
**Pull request by JingyiSu**
Casing to long is fine.
Otherwise, maybe we need to write a new class extends Random() for LongRandom.

### CODE REVIEW

**Comment by psybers** [comment]
Does it make sense to let the cast truncate?  Or should we be rounding the result?

**Comment by JingyiSu** [comment]
I think it's fine. Casting from double to long in java will drop the decimal digits of a number. 
I did a simple test:

```
for (int i = 0; i < 10000; i++) {
	long temp = r.nRand(3);
	if (temp < 1 && temp >= 0)
		b[0]++;
	else if (temp < 2 && temp >= 1)
		b[1]++;
	else if (temp < 3 && temp >= 2)
		b[2]++;
	else
		b[3]++;
} 
for (int j = 0; j < 4; j++) {
	System.out.println(b[j]);
}
```

_**Results:**
3387
3367
3246
0_

Also, I tested it with `(long) (BoaMathIntrinsics.random.nextDouble() * n + 0.5)`.
_**Results:**
1696
3354
3265
1685_

So adding 0.5 will extend the range to the upper bound.

Does it work correctly?

**Comment by psybers** [comment]
No actually. The function returns the inclusive lower bound but exclusive upper bound.

So I think what you have works best!

I think it's fine. Casting from double to long in java will drop the decimal digits of a number.
I did a simple test:

for (int i = 0; i < 10000; i++) {
    long temp = r.nRand(3);
    if (temp < 1 && temp >= 0)
        b[0]++;
    else if (temp < 2 && temp >= 1)
        b[1]++;
    else if (temp < 3 && temp >= 2)
        b[2]++;
    else
        b[3]++;
}
for (int j = 0; j < 4; j++) {
    System.out.println(b[j]);
}


Results:
3387
3367
3246
0

Also, I tested it with (long) (BoaMathIntrinsics.random.nextDouble() * n + 0.5).
Results:
1696
3354
3265
1685

So adding 0.5 will extend the range to the upper bound.

Does it work correctly?

-

**Comment by psybers** [comment]
On line 31 - why did you make this field public?

**Comment by JingyiSu** [comment]
Because I remember you said that when you talked about issue #7(for using the random method  with the seed maybe?) in the meeting.

**Pull request closed without merging**
