### PR TITLE
Add directions to set up boa dev env in Eclipse.

### PR DESCRIPTION
**Pull request by dwtj**
This evening I was trying to set up a development environment for the Boa Compiler within Eclipse in order to browse and read the project's source code. However, because of the somewhat customized `ant build.xml`, I found the process to be a bit more complicated than I expected. I wrote up these directions describing the process which I used to import the project, in case they will be helpful to anyone in the future.

### CODE REVIEW

**Comment by hridesh** [comment]
David, 

Thanks for your contributions. This is a worthwhile addition. I want to help test these directions. On my first attempt, it seems like the linking resources step isn't very straightforward.

**Comment by psybers** [comment]
Would it make sense for you to include the .project file you created in the project's root folder, so then most people can just check the project out and immediately have an Eclipse environment to build the compiler?

**Comment by dwtj** [comment]
@hridesh, you are absolutely right. I have added a commit which clarifies this step.

@psybers, that would indeed be nice and simple for the user. However, I have two concerns.

Firstly, for style, I think it is generally better for style and simplicity to have only one (canonical) description of how to build the project in one repo. It would not be good to have the `.project` and the `build.xml` to be out of sync. This seems especially likely with additions/deletions/updates of dependencies.

Secondly, and more substantively, I think that your suggestion might not work (at least from my first glance at the issue). In the `.project` and `.classpath` files generated by the described process, the links to source files are fully qualified path names. Therefore, if I make one, it will be broken for anyone else who tries to import the Eclipse project. I even tried to modify these files directly to make them relative, but that didn't work. In particular, I tried to

1. copy the `.project` and `.classpath` files into the repo folder,
2. directly modify the `.project` and `.classpath` files to make their paths relative, and
3. import this project into my Eclipse workspace.

When imported, the results were a mess:

screen shot 2016-01-15 at 11 03 44 pm 2

For me, the ideal solution would be able to generate Eclipse project files for the user using an `ant` build target (conventionally named `eclipse`). Then the user would just have to invoke `ant eclipse` and then to import that project into his/her workspace.

**Comment by hridesh** [comment]
Could you please explain as to what was messy about the attached picture? Perhaps with a bit more tweaking we can remove some extraneous file. Introducing a new ant eclipse target is also a good idea. If time permits, you can try that.

**Comment by dwtj** [comment]
@hridesh. Sure, sorry for being unclear. The linked directories (above "Referenced Libraries") are all broken links (indicated by the tiny exclamation marks). None of the source files are actually found by Eclipse, so nothing is being compiled. Even `ant` won't work.

However, I now have some ideas about how to make a `.project` and `.classpath` in another way which might be portable (i.e. files with relative paths and suitable for committing to the repo. This should be possible.

Assuming that we can make portable `.project` and `.classpath` files, I still have the same style and dependency management concerns that I had before.

As you said, if time permits, I'll take a look at the `ant eclipse` idea.

**Comment by aore** [comment]
I followed these directions, and I think it worked, so I'd recommend adding them to the repo. It'd be good to have this as the root README (or link to this in the README).

**Comment by hridesh** [comment]
Anne, that is a great suggestion. Could you try linking to this in root README?

**Comment by psybers** [comment]
We have no root README.md file yet.  I thought these instructions, along with ones my students are writing/wrote (in the google doc) would become the README.md file.

**Comment by hridesh** [comment]
That is a great idea as well. Anne: could you please add this file as root README.md and submit a pull request ? Robert and his students can then evolve that file.

**Comment by hridesh** [comment]
Let us merge for now. When we have another README file, we can refactor.

**Pull request merged**
