### PR TITLE
Enum type in Boa

### PR DESCRIPTION
**Pull request by ankuraga1508**

### CODE REVIEW

**Comment by psybers** [comment]
With the coming support for tuples, I think this enum support can be cleaned up/simplified considerably.  Essentially your syntax is almost a tuple.  So why not just MAKE IT a tuple, and then add the enum keyword in there?

`type T1 = enum {A = "true", B = "false"};`

could easily be done with tuples syntax:

````
type T1 = enum { A := "true", B := "false" };
t1 := T1.A;
````

So the only thing changed in the parsing is the addition of an enum keyword in front of the tuple.  And then in type checking/codegen etc it may even be ok to just reuse the tuple's support.  The only real change to type checking is that a tuple tagged as an enum, all field selections will return the same type T1 (instead of in this example type string).

**Comment by hridesh** [comment]
Tuple and enum types are fundamentally different in semantic analysis and in generated code. So I would recommend keeping their realization independent unless there is a solid reason to mix them.

On May 12, 2016 11:40 PM, Robert Dyer <notifications@github.com> wrote:

With the coming support for tuples, I think this enum support can be cleaned up/simplified considerably. Essentially your syntax is almost a tuple. So why not just MAKE IT a tuple, and then add the enum keyword in there?

type T1 = enum {A = "true", B = "false"};

could easily be done with tuples syntax:

type T1 = enum { A := "true", B := "false" };
t1 := T1.A;


So the only thing changed in the parsing is the addition of an enum keyword in front of the tuple. And then in type checking/codegen etc it may even be ok to just reuse the tuple's support. The only real change to type checking is that a tuple tagged as an enum, all field selections will return the same type T1 (instead of in this example type string).

**Comment by hridesh** [comment]
Do we have any more discussion on this code?

**Comment by psybers** [comment]
Yes.  What are we doing with all of the existing 'enums' (from protos, e.g. StatementKind, ExpressionKind)?  If we have an official enum type then I think it would make sense to modify the system so those are treated as one of these enums, and not handled in the hackish way they are now.

**Comment by hridesh** [comment]
We can start a separate issue for converting existing enums to this form.

**Comment by hridesh** [comment]
How about couple more test cases, perhaps more complex enums?

**Comment by hridesh** [comment]
Seems like this branch has conflict now. Perhaps it might make sense to review after the conflict is fixed.

**Comment by ankuraga1508** [comment]
Closing this pull request. I made a commit with changed file mode and now when I reverted that commit, somehow changed files are still too many which I didn't change. I will send new pull request for enum types.

**Pull request closed without merging**
