### PR TITLE
cfg graph type added. See test-cfg.boa for basic cfg example

### PR DESCRIPTION
**Pull request by RamIowaStateUniversity**

### CODE REVIEW

**Comment by hridesh** [comment]
There are a number of temporary files with ~ at the end. If you can, please do remove them first so that the commit can be more carefully examined.

**Comment by psybers** [comment]
Can we get a Boa example of how to walk the graph, how to view attributes of nodes/edges, etc?  Right now I am unsure how to use a graph once I request it...

**Comment by RamIowaStateUniversity** [comment]
Temporary files has been removed

**Comment by hridesh** [comment]
Few other small things: could we rename getCfg to getcfg? This is more consistent with the rest of the built-in functions in Boa. Also, could we rename CfgGraph type ControlFlowGraph or CFG preferably the later since the previous name has some redundancies in it.

**Comment by RamIowaStateUniversity** [comment]
- Author tag added
- Naming inconsistencies resolved

**Comment by psybers** [comment]
Is there any reason we are adding a new type to Boa 'list of <x>' instead of using the existing 'array of <x>' type?

**Comment by psybers** [comment]
Graph.java is missing a Javadoc header for the class (including author information).

**Comment by RamIowaStateUniversity** [comment]
"repeated" in proto file expects a list in the generated code rather than
array. So when retrieving nodes of a graph, a list of that type is expected

**Comment by psybers** [comment]
Our existing proto types have repeated fields.  We map them to arrays in the Boa language.

I don’t see a need for list for that reason.  Why else is it being proposed?

**Comment by hridesh** [comment]
Was the issue related to list resolved?

**Comment by RamIowaStateUniversity** [comment]
I checked out the previously written proto files that had repeated field. I
took ast.proto as an example. It had "namespaces" as repeated in AstRoot
class. I checked the corresponding prototuple file written for AstRoot. It
had namespaces field as boaprotolist type. Boaprotolist has java.util.list
as the corresponding java type as per the boa compiler. I have attached the
screentshot highlighting the area I spoke. I may be missing something but
as far as I have seen till now, repeated fields are generated as list
datatype and Boaprotolist is used as the boa type. Please do tell me if I
am looking in the wrong direction.

**Comment by RamIowaStateUniversity** [comment]
Javadoc header issue has been resolved. Thank you for identifying it.

**Comment by psybers** [comment]
These are the parts we are talking about regarding list, that seem unnecessary:

https://github.com/boalang/compiler/pull/8/files#diff-c810409ad8e36d29c52105ea28a46ad2
https://github.com/boalang/compiler/pull/8/files#diff-5fbfb61f2076fa20b9ea8a18f43e5034
https://github.com/boalang/compiler/pull/8/files#diff-3c901b1d8b6e12554e398a99a01bb3d5R171
https://github.com/boalang/compiler/pull/8/files#diff-b2518fb52dfff23514862c09e0563679

and I am sure there are others.

**Comment by RamIowaStateUniversity** [comment]
Thanks Dr.Dyer. I now understood why list was redundant and changed the
compiler code according to that. The list issue has now been resolved.

**Comment by psybers** [comment]
What is this change: https://github.com/boalang/compiler/pull/8/files#diff-93685487a551a3263ce032c918dc5b94L52

The master branch has this field set as an int32, while the older (released) compilers have it as string.

Going forward however, it should be int32.  And it seems the branch you are trying to merge into has it that way.  Why was this changed?

**Comment by psybers** [comment]
Remove this change: https://github.com/boalang/compiler/pull/8/files#diff-c810409ad8e36d29c52105ea28a46ad2

**Comment by psybers** [comment]
I forget where the discussion took place (email?), but we had discussed at one point about generalizing this code.  So instead of the more specific 'CFG' in the name everywhere, you have just a 'Graph' and a 'GraphEdge'/'GraphNode' (or Edge/Node).

**Comment by psybers** [comment]
Why are these files modified to *only* add you as an author?

src/java/boa/compiler/visitors/AbstractVisitor.java
src/java/boa/compiler/visitors/AbstractVisitorNoArg.java
src/java/boa/compiler/visitors/AbstractVisitorNoReturn.java
src/java/boa/compiler/visitors/CodeGeneratingVisitor.java
src/java/boa/compiler/visitors/TypeCheckingVisitor.java

**Comment by psybers** [comment]
Why was this import added?

https://github.com/boalang/compiler/pull/8/files#diff-093fbf49a65c683bee84cfb62a2a598dR29

**Comment by hridesh** [comment]
Generic graph support was not requested for this modification request. This MR is meant to support domain-specific graphs.

**Comment by psybers** [comment]
Should this build on top of the generic graph support?  Should we finish the generic graph support first, and then modify this pull request to build on top of it?

**Comment by hridesh** [comment]
Unfortunately, there is not much to be gained by delaying this further. We can revisit, and refactor as needed in future.

**Comment by RamIowaStateUniversity** [comment]
I think the imports and author tags were added when I was modifying the
respective files but then later removed those changes. I have now removed
all the unwanted imports and author tags.

**Pull request merged**
